# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b3cec1de84fa2b37d77c89a5811112afb39317ae0e4164843dc05ff8b7dd87568279b9415b0ce734d10d05905f03c54b2e01eb1dcc41faf4bbae8d802359ec

test:
  secret_key_base: 66905e14b221a8064edf733b60fa57cc9bf3a239622e63fdf1ff2e9fc1ee311e2da8190a47d899e9b8166b98cb91173474f0b2b31114e9f4110b33e674267889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
